### ISSUE TITLE
New project creation fails - Fabric8ForgeService raises 500 error code

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1488]
Steps to reproduce:
* Creaet new space
* In that space - "add to space" - creaet a new project - accept all defaults (basic Vert.X)
* Project creation fails - this error is returned to the user: 

```
origin = Fabric8ForgeService
message = An unexpected server side forge api error occurred
inner = 
httpError = 
status = 500
statusText = Internal Server Error
url = https://forge.api.openshift.io/forge/commands/fabric8-new-project/execute
```

Everything in openshift looks OK - other than the Jenkins pod log shows this error:

```
Jun 09, 2017 4:41:07 PM io.fabric8.jenkins.openshiftsync.BuildWatcher$1 doRun
SEVERE: Failed to load initial Builds: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:483)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:60)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:78)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: timeout
```

**Comment by corinnekrych** [comment]
@ldimaggi locally with the latest code from fabric8-ui I from master, I can create a quickstart ok.
I don't think this is an issue for fabric8-ui.
