### ISSUE TITLE
Repository name pattern - for a user account continuously appends new project names until user is unable to create new project

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1498]
Test user account 'almighytest' is currently unable to create a new project. The error logged in the Forge log (see below) indicates that a read attempt is being made on a closed socket. 

I am not able to recreate this error with other accounts - it looks like this user account is hitting a path that other accounts are not.

![screenshot from 2017-06-12 14-16-18](https://user-images.githubusercontent.com/642621/27048421-ba6b088e-4f79-11e7-9741-8f440aee24b7.png)

Forge log:

```
2017-06-12 17:57:07,812 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-63) Creating github repository user/burrtest99
2017-06-12 17:57:08,413 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-63) Created repository: https://github.com/almightytest/burrtest99
2017-06-12 17:57:08,415 INFO  [io.fabric8.project.support.GitUtils] (default task-63) Trusting all SSL certificates
2017-06-12 17:57:08,418 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-63) Initialised an empty git configuration repo at /tmp/projectDir7110613144287159132/burrtest99
2017-06-12 17:57:08,419 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-63) About to git commit and push to: https://github.com/almightytest/burrtest99.git and remote name origin
2017-06-12 17:57:08,448 INFO  [io.fabric8.project.support.GitUtils] (default task-63) Using UsernamePasswordCredentialsProvider{user: almightytest, password length: 40}
2017-06-12 17:57:08,513 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-63) Caught a transport exception: org.eclipse.jgit.api.errors.TransportException: https://github.com/almightytest/burrtest99.git: https://github.com/almightytest/burrtest99.git/info/refs?service=git-receive-pack not found so retrying
2017-06-12 17:57:09,019 INFO  [io.fabric8.project.support.GitUtils] (default task-63) Using UsernamePasswordCredentialsProvider{user: almightytest, password length: 40}
2017-06-12 17:57:10,787 INFO  [io.fabric8.project.support.BuildConfigHelper] (default task-63) Creating a BuildConfig for namespace: almusertest1 project: burrtest99
2017-06-12 17:57:10,821 INFO  [io.fabric8.kubernetes.api.Controller] (default task-63) Using project: almusertest1
2017-06-12 17:57:11,134 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-63) Got response code from Jenkins looking up credential: 200 message: OK from URL: https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/credentials/store/system/domain/_/credentials/cd-github/ result: null
2017-06-12 17:57:11,263 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-63) Response from https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/almightytest/config.xml is 200 OK
2017-06-12 17:57:11,264 WARN  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-63) Failed to get github org job at https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/almightytest/config.xml. Probably does not exist? javax.ws.rs.ProcessingException: org.jboss.resteasy.spi.ReaderException: java.net.SocketException: Socket is closed: javax.ws.rs.ProcessingException: org.jboss.resteasy.spi.ReaderException: java.net.SocketException: Socket is closed
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:285)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:181)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:219)
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep.ensureJenkinsCDOrganisationJobCreated(CreateBuildConfigStep.java:709)
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep.execute(CreateBuildConfigStep.java:321)
	at sun.reflect.GeneratedMethodAccessor560.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep_$$_javassist_d1eb6fe8-6b9e-4d17-bd74-65ce26395d8c.execute(CreateBuildConfigStep_$$_javassist_d1eb6fe8-6b9e-4d17-bd74-65ce26395d8c.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:157)
	at sun.reflect.GeneratedMethodAccessor664.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_cac8cc56-801a-47a3-b86d-6a08bb873ad7.execute(CommandController_$$_javassist_cac8cc56-801a-47a3-b86d-6a08bb873ad7.java)
	at org.obsidiantoaster.generator.rest.ObsidianResource.executeCommandJson(ObsidianResource.java:483)
	at org.obsidiantoaster.generator.rest.ObsidianResource$Proxy$_$$_WeldClientProxy.executeCommandJson(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor663.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.resteasy.spi.ReaderException: java.net.SocketException: Socket is closed
	at org.jboss.resteasy.plugins.providers.DocumentProvider.readFrom(DocumentProvider.java:113)
	at org.jboss.resteasy.plugins.providers.DocumentProvider.readFrom(DocumentProvider.java:36)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:61)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:53)
	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPDecodingInterceptor.aroundReadFrom(GZIPDecodingInterceptor.java:59)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:55)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:251)
	... 73 more
Caused by: java.net.SocketException: Socket is closed
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1532)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:95)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:206)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2919)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:302)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.arrangeCapacity(XMLEntityScanner.java:1761)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipString(XMLEntityScanner.java:1799)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1748)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.jboss.resteasy.plugins.providers.DocumentProvider.readFrom(DocumentProvider.java:109)
	... 79 more

2017-06-12 17:57:11,397 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-63) Response from https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest is 400 Bad Request
2017-06-12 17:57:11,397 WARN  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-63) Failed to process https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest and got status: 400 Bad Request
2017-06-12 17:57:11,397 ERROR [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-63) Failed to create Jenkins Organisation job: java.lang.IllegalStateException: Failed to create the GitHub Org Job at https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest. javax.ws.rs.WebApplicationException: Failed to process https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest and got status: 400 Bad Request: java.lang.IllegalStateException: Failed to create the GitHub Org Job at https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest. javax.ws.rs.WebApplicationException: Failed to process https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest and got status: 400 Bad Request
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep.ensureJenkinsCDOrganisationJobCreated(CreateBuildConfigStep.java:737)
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep.execute(CreateBuildConfigStep.java:321)
	at sun.reflect.GeneratedMethodAccessor560.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep_$$_javassist_d1eb6fe8-6b9e-4d17-bd74-65ce26395d8c.execute(CreateBuildConfigStep_$$_javassist_d1eb6fe8-6b9e-4d17-bd74-65ce26395d8c.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:157)
	at sun.reflect.GeneratedMethodAccessor664.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_cac8cc56-801a-47a3-b86d-6a08bb873ad7.execute(CommandController_$$_javassist_cac8cc56-801a-47a3-b86d-6a08bb873ad7.java)
	at org.obsidiantoaster.generator.rest.ObsidianResource.executeCommandJson(ObsidianResource.java:483)
	at org.obsidiantoaster.generator.rest.ObsidianResource$Proxy$_$$_WeldClientProxy.executeCommandJson(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor663.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.WebApplicationException: Failed to process https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest and got status: 400 Bad Request
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep.invokeRequestWithRedirectResponse(CreateBuildConfigStep.java:820)
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep.ensureJenkinsCDOrganisationJobCreated(CreateBuildConfigStep.java:732)
	... 70 more

2017-06-12 17:57:11,546 WARN  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-63) Already created build almusertest1/burrtest99 so returning

```

**Comment by ldimaggi** [comment]
https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/kubernetes/CreateBuildConfigStep.java#L324

**Comment by ldimaggi** [comment]
Look here:

https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/almightytest/config.xml

Under: 

```
<scanCredentialsId>cd-github</scanCredentialsId>
<checkoutCredentialsId>SAME</checkoutCredentialsId>
<pattern>
```

Has the account hit a token length error? That would explain why the failure is unique to this account.

**Comment by ldimaggi** [comment]
```
<scanCredentialsId>cd-github</scanCredentialsId>
<checkoutCredentialsId>SAME</checkoutCredentialsId>
<pattern>
testmay161494943323139|testmay161494944689513|testmay161494947418136|testmay161494948295736|testmay161494958589548|testmay161494958680703|testmay171495002041416|testmay181495117035915|testmay181495117966892|testmay181495119456739|testmay181495119725303|testmay181495119867745|testmay181495119991442|testmay181495120144379|testmay181495120227906|testmay181495120431544|testmay181495120507669|testmay181495120599413|testmay181495120670804|testmay181495120743354|testmay181495120821416|testmay181495120905396|testmay181495121017016|testmay181495121095970|testmay181495121173199|testmay181495121257507|testmay181495121417373|testmay181495122259974|testmay181495122422601|testmay181495122521550|testmay181495122591814|testmay181495122790732|testmay181495122963643|testmay181495123196381|testmay181495123273830|testmay181495125109518|testmay181495125390082|testmay181495125572385|testmay181495126430461|testmay181495126940844|testmay181495127732513|testmay181495127832570|testmay181495127985074|testmay181495128105555|testmay181495128260396|testmay181495128483352|testmay181495133421020|testmay181495134063355|testmay181495162529214|testmay191495252035878|testmay201495293582966|testmay201495297343736|testmay201495299596241|testmay221495432428888|testmay221495458103596|testmay221495458641852|testmay221495460002807|testmay231495550586333|testmay231495553221842|testmay231495554218802|testmay231495554639206|testmay231495557764665|testmay231495558732429|testmay231495561363828|testmay231495564055886|testmay231495564974717|testmay231495565569914|testmay231495568570684|testmay231495572170622|testmay231495575754361|testmay231495579354600|testmay231495582955385|testmay241495586561758|testmay241495590171951|testmay241495593793940|testmay251495716647663|testmay251495721834564|testmay251495723120361|testmay251495727119383|testmay251495730559027|testmay251495734395493
```

And so forth.....

**Comment by ldimaggi** [comment]
The issue is that every time a user creates a new project, the project name is appended to the Repository name pattern - eventually, attempts to create new projects fail.

**Comment by jstrachan** [comment]
its worth noting that the new tenant should remove project names from this pattern when the Pipeline is deleted (the underlying BC)

**Comment by jstrachan** [comment]
issue now fixed with the latest tenant. Though its worth clearing out or deleting the Jenkins github org job in test cases
